sbatch -o log/1A23A.out -e log/1A23A.err da_workflow.sh 1A23A
sbatch -o log/1A43A.out -e log/1A43A.err da_workflow.sh 1A43A
sbatch -o log/1AARA.out -e log/1AARA.err da_workflow.sh 1AARA
sbatch -o log/1AG2A.out -e log/1AG2A.err da_workflow.sh 1AG2A
sbatch -o log/1AJ3A.out -e log/1AJ3A.err da_workflow.sh 1AJ3A
sbatch -o log/1AKKA.out -e log/1AKKA.err da_workflow.sh 1AKKA
sbatch -o log/1AM7A.out -e log/1AM7A.err da_workflow.sh 1AM7A
sbatch -o log/1ANKA.out -e log/1ANKA.err da_workflow.sh 1ANKA
sbatch -o log/1AONO.out -e log/1AONO.err da_workflow.sh 1AONO
sbatch -o log/1APSA.out -e log/1APSA.err da_workflow.sh 1APSA
sbatch -o log/1ARRA.out -e log/1ARRA.err da_workflow.sh 1ARRA
sbatch -o log/1AV1A.out -e log/1AV1A.err da_workflow.sh 1AV1A
sbatch -o log/1AXBA.out -e log/1AXBA.err da_workflow.sh 1AXBA
sbatch -o log/1AYFA.out -e log/1AYFA.err da_workflow.sh 1AYFA
sbatch -o log/1AZPA.out -e log/1AZPA.err da_workflow.sh 1AZPA
sbatch -o log/1B0OA.out -e log/1B0OA.err da_workflow.sh 1B0OA
sbatch -o log/1B26A.out -e log/1B26A.err da_workflow.sh 1B26A
sbatch -o log/1B5MA.out -e log/1B5MA.err da_workflow.sh 1B5MA
sbatch -o log/1BLCA.out -e log/1BLCA.err da_workflow.sh 1BLCA
sbatch -o log/1BNLA.out -e log/1BNLA.err da_workflow.sh 1BNLA
sbatch -o log/1BOYA.out -e log/1BOYA.err da_workflow.sh 1BOYA
sbatch -o log/1BP2A.out -e log/1BP2A.err da_workflow.sh 1BP2A
sbatch -o log/1BTAA.out -e log/1BTAA.err da_workflow.sh 1BTAA
sbatch -o log/1C2RA.out -e log/1C2RA.err da_workflow.sh 1C2RA
sbatch -o log/1C5GA.out -e log/1C5GA.err da_workflow.sh 1C5GA
sbatch -o log/1C9OA.out -e log/1C9OA.err da_workflow.sh 1C9OA
sbatch -o log/1CAHA.out -e log/1CAHA.err da_workflow.sh 1CAHA
sbatch -o log/1CHKA.out -e log/1CHKA.err da_workflow.sh 1CHKA
sbatch -o log/1CLWA.out -e log/1CLWA.err da_workflow.sh 1CLWA
sbatch -o log/1CSPA.out -e log/1CSPA.err da_workflow.sh 1CSPA
sbatch -o log/1CYOA.out -e log/1CYOA.err da_workflow.sh 1CYOA
sbatch -o log/1DILA.out -e log/1DILA.err da_workflow.sh 1DILA
sbatch -o log/1DIVA.out -e log/1DIVA.err da_workflow.sh 1DIVA
sbatch -o log/1DKTA.out -e log/1DKTA.err da_workflow.sh 1DKTA
sbatch -o log/1DPMA.out -e log/1DPMA.err da_workflow.sh 1DPMA
sbatch -o log/1FEPA.out -e log/1FEPA.err da_workflow.sh 1FEPA
sbatch -o log/1FKJA.out -e log/1FKJA.err da_workflow.sh 1FKJA
sbatch -o log/1FLVA.out -e log/1FLVA.err da_workflow.sh 1FLVA
sbatch -o log/1FNFA.out -e log/1FNFA.err da_workflow.sh 1FNFA
sbatch -o log/1FRDA.out -e log/1FRDA.err da_workflow.sh 1FRDA
sbatch -o log/1FTGA.out -e log/1FTGA.err da_workflow.sh 1FTGA
sbatch -o log/1FXAA.out -e log/1FXAA.err da_workflow.sh 1FXAA
sbatch -o log/1G6NA.out -e log/1G6NA.err da_workflow.sh 1G6NA
sbatch -o log/1H7MA.out -e log/1H7MA.err da_workflow.sh 1H7MA
sbatch -o log/1HK0X.out -e log/1HK0X.err da_workflow.sh 1HK0X
sbatch -o log/1HMEA.out -e log/1HMEA.err da_workflow.sh 1HMEA
sbatch -o log/1HNGA.out -e log/1HNGA.err da_workflow.sh 1HNGA
sbatch -o log/1HTIA.out -e log/1HTIA.err da_workflow.sh 1HTIA
sbatch -o log/1I5TA.out -e log/1I5TA.err da_workflow.sh 1I5TA
sbatch -o log/1IDSA.out -e log/1IDSA.err da_workflow.sh 1IDSA
sbatch -o log/1IFBA.out -e log/1IFBA.err da_workflow.sh 1IFBA
sbatch -o log/1IGVA.out -e log/1IGVA.err da_workflow.sh 1IGVA
sbatch -o log/1IMQA.out -e log/1IMQA.err da_workflow.sh 1IMQA
sbatch -o log/1IO2A.out -e log/1IO2A.err da_workflow.sh 1IO2A
sbatch -o log/1IR3A.out -e log/1IR3A.err da_workflow.sh 1IR3A
sbatch -o log/1IROA.out -e log/1IROA.err da_workflow.sh 1IROA
sbatch -o log/1KDXA.out -e log/1KDXA.err da_workflow.sh 1KDXA
sbatch -o log/1KFWA.out -e log/1KFWA.err da_workflow.sh 1KFWA
sbatch -o log/1LS4A.out -e log/1LS4A.err da_workflow.sh 1LS4A
sbatch -o log/1LVEA.out -e log/1LVEA.err da_workflow.sh 1LVEA
sbatch -o log/1MBGA.out -e log/1MBGA.err da_workflow.sh 1MBGA
sbatch -o log/1MJCA.out -e log/1MJCA.err da_workflow.sh 1MJCA
sbatch -o log/1MSIA.out -e log/1MSIA.err da_workflow.sh 1MSIA
sbatch -o log/1N0JA.out -e log/1N0JA.err da_workflow.sh 1N0JA
sbatch -o log/1OIAA.out -e log/1OIAA.err da_workflow.sh 1OIAA
sbatch -o log/1ONCA.out -e log/1ONCA.err da_workflow.sh 1ONCA
sbatch -o log/1OTRB.out -e log/1OTRB.err da_workflow.sh 1OTRB
sbatch -o log/1PGAA.out -e log/1PGAA.err da_workflow.sh 1PGAA
sbatch -o log/1PINA.out -e log/1PINA.err da_workflow.sh 1PINA
sbatch -o log/1POHA.out -e log/1POHA.err da_workflow.sh 1POHA
sbatch -o log/1QGVA.out -e log/1QGVA.err da_workflow.sh 1QGVA
sbatch -o log/1QJPA.out -e log/1QJPA.err da_workflow.sh 1QJPA
sbatch -o log/1QLPA.out -e log/1QLPA.err da_workflow.sh 1QLPA
sbatch -o log/1QQVA.out -e log/1QQVA.err da_workflow.sh 1QQVA
sbatch -o log/1RHGA.out -e log/1RHGA.err da_workflow.sh 1RHGA
sbatch -o log/1RISA.out -e log/1RISA.err da_workflow.sh 1RISA
sbatch -o log/1ROPA.out -e log/1ROPA.err da_workflow.sh 1ROPA
sbatch -o log/1RROA.out -e log/1RROA.err da_workflow.sh 1RROA
sbatch -o log/1RTBA.out -e log/1RTBA.err da_workflow.sh 1RTBA
sbatch -o log/1RTP1.out -e log/1RTP1.err da_workflow.sh 1RTP1
sbatch -o log/1RX4A.out -e log/1RX4A.err da_workflow.sh 1RX4A
sbatch -o log/1SAKA.out -e log/1SAKA.err da_workflow.sh 1SAKA
sbatch -o log/1SCEA.out -e log/1SCEA.err da_workflow.sh 1SCEA
sbatch -o log/1SHFA.out -e log/1SHFA.err da_workflow.sh 1SHFA
sbatch -o log/1SHGA.out -e log/1SHGA.err da_workflow.sh 1SHGA
sbatch -o log/1SSOA.out -e log/1SSOA.err da_workflow.sh 1SSOA
sbatch -o log/1SUPA.out -e log/1SUPA.err da_workflow.sh 1SUPA
sbatch -o log/1TENA.out -e log/1TENA.err da_workflow.sh 1TENA
sbatch -o log/1THQA.out -e log/1THQA.err da_workflow.sh 1THQA
sbatch -o log/1TITA.out -e log/1TITA.err da_workflow.sh 1TITA
sbatch -o log/1TPKA.out -e log/1TPKA.err da_workflow.sh 1TPKA
sbatch -o log/1TTGA.out -e log/1TTGA.err da_workflow.sh 1TTGA
sbatch -o log/1UBQA.out -e log/1UBQA.err da_workflow.sh 1UBQA
sbatch -o log/1UWOA.out -e log/1UWOA.err da_workflow.sh 1UWOA
sbatch -o log/1UZCA.out -e log/1UZCA.err da_workflow.sh 1UZCA
sbatch -o log/1W4HA.out -e log/1W4HA.err da_workflow.sh 1W4HA
sbatch -o log/1WQ5A.out -e log/1WQ5A.err da_workflow.sh 1WQ5A
sbatch -o log/1YCCA.out -e log/1YCCA.err da_workflow.sh 1YCCA
sbatch -o log/1YEAA.out -e log/1YEAA.err da_workflow.sh 1YEAA
sbatch -o log/1ZNJA.out -e log/1ZNJA.err da_workflow.sh 1ZNJA
sbatch -o log/1ZNJB.out -e log/1ZNJB.err da_workflow.sh 1ZNJB
sbatch -o log/2A36A.out -e log/2A36A.err da_workflow.sh 2A36A
sbatch -o log/2ABDA.out -e log/2ABDA.err da_workflow.sh 2ABDA
sbatch -o log/2ADAA.out -e log/2ADAA.err da_workflow.sh 2ADAA
sbatch -o log/2AFGA.out -e log/2AFGA.err da_workflow.sh 2AFGA
sbatch -o log/2AKYA.out -e log/2AKYA.err da_workflow.sh 2AKYA
sbatch -o log/2BRDA.out -e log/2BRDA.err da_workflow.sh 2BRDA
sbatch -o log/2CI2I.out -e log/2CI2I.err da_workflow.sh 2CI2I
sbatch -o log/2CRKA.out -e log/2CRKA.err da_workflow.sh 2CRKA
sbatch -o log/2HMBA.out -e log/2HMBA.err da_workflow.sh 2HMBA
sbatch -o log/2HPRA.out -e log/2HPRA.err da_workflow.sh 2HPRA
sbatch -o log/2IFBA.out -e log/2IFBA.err da_workflow.sh 2IFBA
sbatch -o log/2IMMA.out -e log/2IMMA.err da_workflow.sh 2IMMA
sbatch -o log/2Q98A.out -e log/2Q98A.err da_workflow.sh 2Q98A
sbatch -o log/2TRXA.out -e log/2TRXA.err da_workflow.sh 2TRXA
sbatch -o log/2WSYA.out -e log/2WSYA.err da_workflow.sh 2WSYA
sbatch -o log/2ZTAA.out -e log/2ZTAA.err da_workflow.sh 2ZTAA
sbatch -o log/3BLSA.out -e log/3BLSA.err da_workflow.sh 3BLSA
sbatch -o log/3D2AA.out -e log/3D2AA.err da_workflow.sh 3D2AA
sbatch -o log/3HHRA.out -e log/3HHRA.err da_workflow.sh 3HHRA
sbatch -o log/3MBPA.out -e log/3MBPA.err da_workflow.sh 3MBPA
sbatch -o log/3PGKA.out -e log/3PGKA.err da_workflow.sh 3PGKA
sbatch -o log/3SSIA.out -e log/3SSIA.err da_workflow.sh 3SSIA
sbatch -o log/451CA.out -e log/451CA.err da_workflow.sh 451CA
sbatch -o log/4BLMA.out -e log/4BLMA.err da_workflow.sh 4BLMA
sbatch -o log/5AZUA.out -e log/5AZUA.err da_workflow.sh 5AZUA
sbatch -o log/5CROA.out -e log/5CROA.err da_workflow.sh 5CROA
