sbatch -o log/1A23.out -e log/1A23.err da_workflow.sh 1A23
sbatch -o log/1A43.out -e log/1A43.err da_workflow.sh 1A43
sbatch -o log/1AAR.out -e log/1AAR.err da_workflow.sh 1AAR
sbatch -o log/1AG2.out -e log/1AG2.err da_workflow.sh 1AG2
sbatch -o log/1AJ3.out -e log/1AJ3.err da_workflow.sh 1AJ3
sbatch -o log/1AKK.out -e log/1AKK.err da_workflow.sh 1AKK
sbatch -o log/1AM7.out -e log/1AM7.err da_workflow.sh 1AM7
sbatch -o log/1ANK.out -e log/1ANK.err da_workflow.sh 1ANK
sbatch -o log/1AON.out -e log/1AON.err da_workflow.sh 1AON
sbatch -o log/1APS.out -e log/1APS.err da_workflow.sh 1APS
sbatch -o log/1ARR.out -e log/1ARR.err da_workflow.sh 1ARR
sbatch -o log/1AV1.out -e log/1AV1.err da_workflow.sh 1AV1
sbatch -o log/1AXB.out -e log/1AXB.err da_workflow.sh 1AXB
sbatch -o log/1AYF.out -e log/1AYF.err da_workflow.sh 1AYF
sbatch -o log/1AZP.out -e log/1AZP.err da_workflow.sh 1AZP
sbatch -o log/1B0O.out -e log/1B0O.err da_workflow.sh 1B0O
sbatch -o log/1B26.out -e log/1B26.err da_workflow.sh 1B26
sbatch -o log/1B5M.out -e log/1B5M.err da_workflow.sh 1B5M
sbatch -o log/1BLC.out -e log/1BLC.err da_workflow.sh 1BLC
sbatch -o log/1BNL.out -e log/1BNL.err da_workflow.sh 1BNL
sbatch -o log/1BOY.out -e log/1BOY.err da_workflow.sh 1BOY
sbatch -o log/1BP2.out -e log/1BP2.err da_workflow.sh 1BP2
sbatch -o log/1BTA.out -e log/1BTA.err da_workflow.sh 1BTA
sbatch -o log/1C2R.out -e log/1C2R.err da_workflow.sh 1C2R
sbatch -o log/1C5G.out -e log/1C5G.err da_workflow.sh 1C5G
sbatch -o log/1C9O.out -e log/1C9O.err da_workflow.sh 1C9O
sbatch -o log/1CAH.out -e log/1CAH.err da_workflow.sh 1CAH
sbatch -o log/1CHK.out -e log/1CHK.err da_workflow.sh 1CHK
sbatch -o log/1CLW.out -e log/1CLW.err da_workflow.sh 1CLW
sbatch -o log/1CSP.out -e log/1CSP.err da_workflow.sh 1CSP
sbatch -o log/1CYO.out -e log/1CYO.err da_workflow.sh 1CYO
sbatch -o log/1DIL.out -e log/1DIL.err da_workflow.sh 1DIL
sbatch -o log/1DIV.out -e log/1DIV.err da_workflow.sh 1DIV
sbatch -o log/1DKT.out -e log/1DKT.err da_workflow.sh 1DKT
sbatch -o log/1DPM.out -e log/1DPM.err da_workflow.sh 1DPM
sbatch -o log/1FEP.out -e log/1FEP.err da_workflow.sh 1FEP
sbatch -o log/1FKJ.out -e log/1FKJ.err da_workflow.sh 1FKJ
sbatch -o log/1FLV.out -e log/1FLV.err da_workflow.sh 1FLV
sbatch -o log/1FNF.out -e log/1FNF.err da_workflow.sh 1FNF
sbatch -o log/1FRD.out -e log/1FRD.err da_workflow.sh 1FRD
sbatch -o log/1FTG.out -e log/1FTG.err da_workflow.sh 1FTG
sbatch -o log/1FXA.out -e log/1FXA.err da_workflow.sh 1FXA
sbatch -o log/1G6N.out -e log/1G6N.err da_workflow.sh 1G6N
sbatch -o log/1H7M.out -e log/1H7M.err da_workflow.sh 1H7M
sbatch -o log/1HK0.out -e log/1HK0.err da_workflow.sh 1HK0
sbatch -o log/1HME.out -e log/1HME.err da_workflow.sh 1HME
sbatch -o log/1HNG.out -e log/1HNG.err da_workflow.sh 1HNG
sbatch -o log/1HTI.out -e log/1HTI.err da_workflow.sh 1HTI
sbatch -o log/1I5T.out -e log/1I5T.err da_workflow.sh 1I5T
sbatch -o log/1IDS.out -e log/1IDS.err da_workflow.sh 1IDS
sbatch -o log/1IFB.out -e log/1IFB.err da_workflow.sh 1IFB
sbatch -o log/1IGV.out -e log/1IGV.err da_workflow.sh 1IGV
sbatch -o log/1IMQ.out -e log/1IMQ.err da_workflow.sh 1IMQ
sbatch -o log/1IO2.out -e log/1IO2.err da_workflow.sh 1IO2
sbatch -o log/1IR3.out -e log/1IR3.err da_workflow.sh 1IR3
sbatch -o log/1IRO.out -e log/1IRO.err da_workflow.sh 1IRO
sbatch -o log/1KDX.out -e log/1KDX.err da_workflow.sh 1KDX
sbatch -o log/1KFW.out -e log/1KFW.err da_workflow.sh 1KFW
sbatch -o log/1LS4.out -e log/1LS4.err da_workflow.sh 1LS4
sbatch -o log/1LVE.out -e log/1LVE.err da_workflow.sh 1LVE
sbatch -o log/1MBG.out -e log/1MBG.err da_workflow.sh 1MBG
sbatch -o log/1MJC.out -e log/1MJC.err da_workflow.sh 1MJC
sbatch -o log/1MSI.out -e log/1MSI.err da_workflow.sh 1MSI
sbatch -o log/1N0J.out -e log/1N0J.err da_workflow.sh 1N0J
sbatch -o log/1OIA.out -e log/1OIA.err da_workflow.sh 1OIA
sbatch -o log/1ONC.out -e log/1ONC.err da_workflow.sh 1ONC
sbatch -o log/1OTR.out -e log/1OTR.err da_workflow.sh 1OTR
sbatch -o log/1PGA.out -e log/1PGA.err da_workflow.sh 1PGA
sbatch -o log/1PIN.out -e log/1PIN.err da_workflow.sh 1PIN
sbatch -o log/1POH.out -e log/1POH.err da_workflow.sh 1POH
sbatch -o log/1QGV.out -e log/1QGV.err da_workflow.sh 1QGV
sbatch -o log/1QJP.out -e log/1QJP.err da_workflow.sh 1QJP
sbatch -o log/1QLP.out -e log/1QLP.err da_workflow.sh 1QLP
sbatch -o log/1QQV.out -e log/1QQV.err da_workflow.sh 1QQV
sbatch -o log/1RHG.out -e log/1RHG.err da_workflow.sh 1RHG
sbatch -o log/1RIS.out -e log/1RIS.err da_workflow.sh 1RIS
sbatch -o log/1ROP.out -e log/1ROP.err da_workflow.sh 1ROP
sbatch -o log/1RRO.out -e log/1RRO.err da_workflow.sh 1RRO
sbatch -o log/1RTB.out -e log/1RTB.err da_workflow.sh 1RTB
sbatch -o log/1RTP.out -e log/1RTP.err da_workflow.sh 1RTP
sbatch -o log/1RX4.out -e log/1RX4.err da_workflow.sh 1RX4
sbatch -o log/1SAK.out -e log/1SAK.err da_workflow.sh 1SAK
sbatch -o log/1SCE.out -e log/1SCE.err da_workflow.sh 1SCE
sbatch -o log/1SHF.out -e log/1SHF.err da_workflow.sh 1SHF
sbatch -o log/1SHG.out -e log/1SHG.err da_workflow.sh 1SHG
sbatch -o log/1SSO.out -e log/1SSO.err da_workflow.sh 1SSO
sbatch -o log/1SUP.out -e log/1SUP.err da_workflow.sh 1SUP
sbatch -o log/1TEN.out -e log/1TEN.err da_workflow.sh 1TEN
sbatch -o log/1THQ.out -e log/1THQ.err da_workflow.sh 1THQ
sbatch -o log/1TIT.out -e log/1TIT.err da_workflow.sh 1TIT
sbatch -o log/1TPK.out -e log/1TPK.err da_workflow.sh 1TPK
sbatch -o log/1TTG.out -e log/1TTG.err da_workflow.sh 1TTG
sbatch -o log/1UBQ.out -e log/1UBQ.err da_workflow.sh 1UBQ
sbatch -o log/1UWO.out -e log/1UWO.err da_workflow.sh 1UWO
sbatch -o log/1UZC.out -e log/1UZC.err da_workflow.sh 1UZC
sbatch -o log/1W4H.out -e log/1W4H.err da_workflow.sh 1W4H
sbatch -o log/1WQ5.out -e log/1WQ5.err da_workflow.sh 1WQ5
sbatch -o log/1YCC.out -e log/1YCC.err da_workflow.sh 1YCC
sbatch -o log/1YEA.out -e log/1YEA.err da_workflow.sh 1YEA
sbatch -o log/1ZNJ.out -e log/1ZNJ.err da_workflow.sh 1ZNJ
sbatch -o log/2A36.out -e log/2A36.err da_workflow.sh 2A36
sbatch -o log/2ABD.out -e log/2ABD.err da_workflow.sh 2ABD
sbatch -o log/2ADA.out -e log/2ADA.err da_workflow.sh 2ADA
sbatch -o log/2AFG.out -e log/2AFG.err da_workflow.sh 2AFG
sbatch -o log/2AKY.out -e log/2AKY.err da_workflow.sh 2AKY
sbatch -o log/2BRD.out -e log/2BRD.err da_workflow.sh 2BRD
sbatch -o log/2CI2.out -e log/2CI2.err da_workflow.sh 2CI2
sbatch -o log/2CRK.out -e log/2CRK.err da_workflow.sh 2CRK
sbatch -o log/2HMB.out -e log/2HMB.err da_workflow.sh 2HMB
sbatch -o log/2HPR.out -e log/2HPR.err da_workflow.sh 2HPR
sbatch -o log/2IFB.out -e log/2IFB.err da_workflow.sh 2IFB
sbatch -o log/2IMM.out -e log/2IMM.err da_workflow.sh 2IMM
sbatch -o log/2Q98.out -e log/2Q98.err da_workflow.sh 2Q98
sbatch -o log/2TRX.out -e log/2TRX.err da_workflow.sh 2TRX
sbatch -o log/2WSY.out -e log/2WSY.err da_workflow.sh 2WSY
sbatch -o log/2ZTA.out -e log/2ZTA.err da_workflow.sh 2ZTA
sbatch -o log/3BLS.out -e log/3BLS.err da_workflow.sh 3BLS
sbatch -o log/3D2A.out -e log/3D2A.err da_workflow.sh 3D2A
sbatch -o log/3HHR.out -e log/3HHR.err da_workflow.sh 3HHR
sbatch -o log/3MBP.out -e log/3MBP.err da_workflow.sh 3MBP
sbatch -o log/3PGK.out -e log/3PGK.err da_workflow.sh 3PGK
sbatch -o log/3SSI.out -e log/3SSI.err da_workflow.sh 3SSI
sbatch -o log/451C.out -e log/451C.err da_workflow.sh 451C
sbatch -o log/4BLM.out -e log/4BLM.err da_workflow.sh 4BLM
sbatch -o log/5AZU.out -e log/5AZU.err da_workflow.sh 5AZU
sbatch -o log/5CRO.out -e log/5CRO.err da_workflow.sh 5CRO
